// <auto-generated />
namespace Lab7.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class CreateJobs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateJobs));
        
        string IMigrationMetadata.Id
        {
            get { return "202111261728155_CreateJobs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
