use University;

SELECT f.NAME_FACULTETA, d.NAME_KAFEDRA, 
COUNT(DISTINCT s.GROUP_NAME) AS "Amount of groups", 
COUNT(s.Kod_KAFEDRA) AS "Amount of students in the department" 
FROM FACULTET f, KAFEDRA d, STUDENT s 
WHERE f.KOD_FACULTETA = d.KOD_FACULTETA AND 
d.Kod_KAFEDRA = s.Kod_KAFEDRA AND 
d.NUM_KORPUSA = '1' 
GROUP BY f.NAME_FACULTETA, d.NAME_KAFEDRA;
